-- Run this in Supabase SQL editor.
create extension if not exists pgcrypto;

create table if not exists public.decision_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null default 'Natural language',
  mood text not null default 'Balanced',
  answer text not null,
  conversation jsonb default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.decision_history add column if not exists conversation jsonb default '[]'::jsonb;
alter table public.decision_history alter column category set default 'Natural language';
alter table public.decision_history alter column mood set default 'Balanced';

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  referral_code text unique,
  referred_by uuid references auth.users(id),
  bonus_decisions int not null default 0,
  total_decisions int not null default 0,
  total_votes int not null default 0,
  minds_changed int not null default 0,
  current_streak int not null default 0,
  longest_streak int not null default 0,
  last_active_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists total_votes int not null default 0;
alter table public.profiles add column if not exists minds_changed int not null default 0;
alter table public.profiles add column if not exists current_streak int not null default 0;
alter table public.profiles add column if not exists longest_streak int not null default 0;
alter table public.profiles add column if not exists last_active_date date;

create table if not exists public.group_decisions (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id),
  prompt text not null,
  personality text not null default 'Balanced',
  share_code text unique not null,
  final_answer text,
  created_at timestamptz not null default now()
);

create table if not exists public.group_preferences (
  id bigint generated by default as identity primary key,
  group_id uuid not null references public.group_decisions(id) on delete cascade,
  user_id uuid references auth.users(id),
  nickname text,
  preference text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references auth.users(id) on delete cascade,
  referred_id uuid not null unique references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_dilemmas (
  id bigint generated by default as identity primary key,
  date_key date not null unique,
  question text not null,
  option_a text not null,
  option_b text not null,
  ai_pick text,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_dilemma_votes (
  id bigint generated by default as identity primary key,
  dilemma_id bigint not null references public.daily_dilemmas(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  vote_option text not null check (vote_option in ('A', 'B')),
  created_at timestamptz not null default now(),
  unique (dilemma_id, user_id)
);

create or replace function public.grant_referral_bonus(p_referrer_id uuid, p_referred_id uuid)
returns void
language plpgsql
security definer
as $$
begin
  update public.profiles
  set bonus_decisions = bonus_decisions + 10
  where id in (p_referrer_id, p_referred_id);
end;
$$;

alter table public.decision_history enable row level security;
alter table public.profiles enable row level security;
alter table public.group_decisions enable row level security;
alter table public.group_preferences enable row level security;
alter table public.referrals enable row level security;
alter table public.daily_dilemmas enable row level security;
alter table public.daily_dilemma_votes enable row level security;

drop policy if exists "Users can read their own decision history" on public.decision_history;
drop policy if exists "Users can insert their own decision history" on public.decision_history;

create policy "Users can read their own decision history"
on public.decision_history for select
using (auth.uid() = user_id);

create policy "Users can insert their own decision history"
on public.decision_history for insert
with check (auth.uid() = user_id);

create policy "Users can update own history"
on public.decision_history for update
using (auth.uid() = user_id);

create policy "Profiles are readable by everyone"
on public.profiles for select
using (true);

create policy "Users can insert own profile"
on public.profiles for insert
with check (auth.uid() = id);

create policy "Users can update own profile"
on public.profiles for update
using (auth.uid() = id);

create policy "Group decisions are readable by everyone"
on public.group_decisions for select
using (true);

create policy "Authenticated users can create group decisions"
on public.group_decisions for insert
with check (auth.uid() = owner_id or owner_id is null);

create policy "Owners can update group decisions"
on public.group_decisions for update
using (auth.uid() = owner_id or owner_id is null);

create policy "Group preferences are readable by everyone"
on public.group_preferences for select
using (true);

create policy "Anyone can insert group preferences"
on public.group_preferences for insert
with check (true);

create policy "Referrals visible to involved users"
on public.referrals for select
using (auth.uid() = referrer_id or auth.uid() = referred_id);

create policy "Users can insert referral they are part of"
on public.referrals for insert
with check (auth.uid() = referrer_id or auth.uid() = referred_id);

create policy "Daily dilemmas readable by everyone"
on public.daily_dilemmas for select
using (true);

create policy "Authenticated users can create daily dilemmas"
on public.daily_dilemmas for insert
with check (auth.uid() is not null);

create policy "Authenticated users can update daily dilemmas"
on public.daily_dilemmas for update
using (auth.uid() is not null);

create policy "Daily votes readable by everyone"
on public.daily_dilemma_votes for select
using (true);

create policy "Users can cast own daily vote"
on public.daily_dilemma_votes for insert
with check (auth.uid() = user_id);

create policy "Users can update own daily vote"
on public.daily_dilemma_votes for update
using (auth.uid() = user_id);
