-- Run this in Supabase SQL editor.
create table if not exists public.decision_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  mood text not null,
  answer text not null,
  created_at timestamptz not null default now()
);

alter table public.decision_history enable row level security;

create policy "Users can read their own decision history"
on public.decision_history
for select
using (auth.uid() = user_id);

create policy "Users can insert their own decision history"
on public.decision_history
for insert
with check (auth.uid() = user_id);
