-- Run this in Supabase SQL editor.
create extension if not exists pgcrypto;

create table if not exists public.decision_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null default 'Natural language',
  mood text not null default 'Balanced',
  answer text not null,
  conversation jsonb default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.decision_history add column if not exists conversation jsonb default '[]'::jsonb;
alter table public.decision_history alter column category set default 'Natural language';
alter table public.decision_history alter column mood set default 'Balanced';

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  referral_code text unique,
  referred_by uuid references auth.users(id),
  bonus_decisions int not null default 0,
  total_decisions int not null default 0,
  total_votes int not null default 0,
  minds_changed int not null default 0,
  current_streak int not null default 0,
  longest_streak int not null default 0,
  last_active_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists total_votes int not null default 0;
alter table public.profiles add column if not exists minds_changed int not null default 0;
alter table public.profiles add column if not exists current_streak int not null default 0;
alter table public.profiles add column if not exists longest_streak int not null default 0;
alter table public.profiles add column if not exists last_active_date date;

create table if not exists public.group_decisions (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id),
  prompt text not null,
  personality text not null default 'Balanced',
  share_code text unique not null,
  final_answer text,
  created_at timestamptz not null default now()
);

create table if not exists public.group_preferences (
  id bigint generated by default as identity primary key,
  group_id uuid not null references public.group_decisions(id) on delete cascade,
  user_id uuid references auth.users(id),
  nickname text,
  preference text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references auth.users(id) on delete cascade,
  referred_id uuid not null unique references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_dilemmas (
  id bigint generated by default as identity primary key,
  date_key date not null unique,
  date date,
  question text not null,
  option_a text not null,
  option_b text not null,
  votes_a int not null default 0,
  votes_b int not null default 0,
  ai_pick text,
  created_at timestamptz not null default now()
);

alter table public.daily_dilemmas add column if not exists date date;
alter table public.daily_dilemmas add column if not exists votes_a int not null default 0;
alter table public.daily_dilemmas add column if not exists votes_b int not null default 0;
update public.daily_dilemmas set date = coalesce(date, date_key);
create unique index if not exists daily_dilemmas_date_unique on public.daily_dilemmas (date);

create table if not exists public.daily_dilemma_votes (
  id bigint generated by default as identity primary key,
  dilemma_id bigint not null references public.daily_dilemmas(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  vote_option text not null check (vote_option in ('A', 'B')),
  created_at timestamptz not null default now(),
  unique (dilemma_id, user_id)
);

create or replace function public.sync_daily_dilemma_vote_totals()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    if new.vote_option = 'A' then
      update public.daily_dilemmas set votes_a = votes_a + 1 where id = new.dilemma_id;
    else
      update public.daily_dilemmas set votes_b = votes_b + 1 where id = new.dilemma_id;
    end if;
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if old.vote_option <> new.vote_option then
      if old.vote_option = 'A' then
        update public.daily_dilemmas set votes_a = greatest(votes_a - 1, 0) where id = new.dilemma_id;
      else
        update public.daily_dilemmas set votes_b = greatest(votes_b - 1, 0) where id = new.dilemma_id;
      end if;
      if new.vote_option = 'A' then
        update public.daily_dilemmas set votes_a = votes_a + 1 where id = new.dilemma_id;
      else
        update public.daily_dilemmas set votes_b = votes_b + 1 where id = new.dilemma_id;
      end if;
    end if;
    return new;
  end if;

  return null;
end;
$$;

create or replace function public.increment_daily_dilemma_vote(p_dilemma_id bigint, p_vote_option text)
returns void
language plpgsql
security definer
as $$
begin
  if p_vote_option = 'A' then
    update public.daily_dilemmas
    set votes_a = votes_a + 1
    where id = p_dilemma_id;
  elsif p_vote_option = 'B' then
    update public.daily_dilemmas
    set votes_b = votes_b + 1
    where id = p_dilemma_id;
  else
    raise exception 'Invalid vote option: %', p_vote_option;
  end if;
end;
$$;

drop trigger if exists trg_sync_daily_dilemma_vote_totals on public.daily_dilemma_votes;
create trigger trg_sync_daily_dilemma_vote_totals
after insert or update on public.daily_dilemma_votes
for each row execute function public.sync_daily_dilemma_vote_totals();

insert into public.daily_dilemmas (date, date_key, question, option_a, option_b)
values
  (current_date + 0, current_date + 0, 'Would you rather have unlimited money or unlimited time?', 'Unlimited money', 'Unlimited time'),
  (current_date + 1, current_date + 1, 'Would you quit your job if you won £1 million?', 'Quit and start fresh', 'Keep working with freedom'),
  (current_date + 2, current_date + 2, 'Would you rather be famous or rich?', 'Famous', 'Rich'),
  (current_date + 3, current_date + 3, 'Would you rather live in the city or countryside?', 'City', 'Countryside'),
  (current_date + 4, current_date + 4, 'Would you rather travel the world for a year or buy your dream home now?', 'Travel the world', 'Buy dream home'),
  (current_date + 5, current_date + 5, 'Would you rather work 4 long days or 5 shorter days?', '4 long days', '5 shorter days'),
  (current_date + 6, current_date + 6, 'Would you rather always be 15 minutes early or always exactly on time?', 'Always early', 'Exactly on time'),
  (current_date + 7, current_date + 7, 'Would you rather save aggressively now or enjoy your money more today?', 'Save aggressively', 'Enjoy today'),
  (current_date + 8, current_date + 8, 'Would you rather have one best friend or a big social circle?', 'One best friend', 'Big social circle'),
  (current_date + 9, current_date + 9, 'Would you rather cook every day or order takeout every day?', 'Cook every day', 'Order takeout'),
  (current_date + 10, current_date + 10, 'Would you rather binge a new show or rewatch a comfort classic?', 'New show', 'Comfort classic'),
  (current_date + 11, current_date + 11, 'Would you rather wake up at 5am daily or stay up past midnight daily?', 'Wake at 5am', 'Stay up past midnight'),
  (current_date + 12, current_date + 12, 'Would you rather have perfect health habits or perfect financial habits?', 'Health habits', 'Financial habits'),
  (current_date + 13, current_date + 13, 'Would you rather spend on experiences or things?', 'Experiences', 'Things'),
  (current_date + 14, current_date + 14, 'Would you rather move abroad next year or stay close to family?', 'Move abroad', 'Stay close'),
  (current_date + 15, current_date + 15, 'Would you rather have a stable routine or spontaneous days?', 'Stable routine', 'Spontaneous days'),
  (current_date + 16, current_date + 16, 'Would you rather take a high-risk high-reward role or a secure role?', 'High-risk role', 'Secure role'),
  (current_date + 17, current_date + 17, 'Would you rather go car-free or give up food delivery?', 'Go car-free', 'Give up delivery'),
  (current_date + 18, current_date + 18, 'Would you rather spend your weekend outdoors or indoors recharging?', 'Outdoors', 'Indoors'),
  (current_date + 19, current_date + 19, 'Would you rather have no meetings for a week or no emails for a week?', 'No meetings', 'No emails'),
  (current_date + 20, current_date + 20, 'Would you rather live near work or keep a bigger home further away?', 'Live near work', 'Bigger home'),
  (current_date + 21, current_date + 21, 'Would you rather be debt-free sooner or invest sooner?', 'Be debt-free sooner', 'Invest sooner'),
  (current_date + 22, current_date + 22, 'Would you rather have one long holiday or several short breaks?', 'One long holiday', 'Several short breaks'),
  (current_date + 23, current_date + 23, 'Would you rather give up social media or streaming apps for a month?', 'Give up social media', 'Give up streaming'),
  (current_date + 24, current_date + 24, 'Would you rather eat dessert every day or coffee every day?', 'Dessert every day', 'Coffee every day'),
  (current_date + 25, current_date + 25, 'Would you rather spend less but live smaller or spend more for comfort?', 'Spend less, live smaller', 'Spend more for comfort'),
  (current_date + 26, current_date + 26, 'Would you rather master one skill deeply or learn many skills broadly?', 'One skill deeply', 'Many skills broadly'),
  (current_date + 27, current_date + 27, 'Would you rather work remotely forever or in-office forever?', 'Remote forever', 'In-office forever'),
  (current_date + 28, current_date + 28, 'Would you rather plan every meal or decide meals on the day?', 'Plan every meal', 'Decide on the day'),
  (current_date + 29, current_date + 29, 'Would you rather have more free time or more disposable income right now?', 'More free time', 'More disposable income')
on conflict (date) do nothing;

create table if not exists public.user_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  preference text not null,
  preference_normalized text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, preference_normalized)
);

create table if not exists public.daily_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  usage_date date not null default current_date,
  decision_count int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, usage_date)
);

create table if not exists public.life_mode_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  started_at timestamptz not null default now(),
  ends_at timestamptz not null,
  is_active boolean not null default true,
  recap_json jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.life_mode_decisions (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.life_mode_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  prompt text not null,
  answer text not null,
  created_at timestamptz not null default now()
);

create or replace function public.grant_referral_bonus(p_referrer_id uuid, p_referred_id uuid)
returns void
language plpgsql
security definer
as $$
begin
  update public.profiles
  set bonus_decisions = bonus_decisions + 10
  where id in (p_referrer_id, p_referred_id);
end;
$$;

alter table public.decision_history enable row level security;
alter table public.profiles enable row level security;
alter table public.group_decisions enable row level security;
alter table public.group_preferences enable row level security;
alter table public.referrals enable row level security;
alter table public.daily_dilemmas enable row level security;
alter table public.daily_dilemma_votes enable row level security;
alter table public.user_preferences enable row level security;
alter table public.daily_usage enable row level security;
alter table public.life_mode_sessions enable row level security;
alter table public.life_mode_decisions enable row level security;

drop policy if exists "Users can read their own decision history" on public.decision_history;
drop policy if exists "Users can insert their own decision history" on public.decision_history;
drop policy if exists "Users can update own history" on public.decision_history;
drop policy if exists "Profiles are readable by everyone" on public.profiles;
drop policy if exists "Users can insert own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;
drop policy if exists "Group decisions are readable by everyone" on public.group_decisions;
drop policy if exists "Authenticated users can create group decisions" on public.group_decisions;
drop policy if exists "Owners can update group decisions" on public.group_decisions;
drop policy if exists "Group preferences are readable by everyone" on public.group_preferences;
drop policy if exists "Anyone can insert group preferences" on public.group_preferences;
drop policy if exists "Referrals visible to involved users" on public.referrals;
drop policy if exists "Users can insert referral they are part of" on public.referrals;
drop policy if exists "Daily dilemmas readable by everyone" on public.daily_dilemmas;
drop policy if exists "Authenticated users can create daily dilemmas" on public.daily_dilemmas;
drop policy if exists "Authenticated users can update daily dilemmas" on public.daily_dilemmas;
drop policy if exists "Daily votes readable by everyone" on public.daily_dilemma_votes;
drop policy if exists "Users can cast own daily vote" on public.daily_dilemma_votes;
drop policy if exists "Users can update own daily vote" on public.daily_dilemma_votes;
drop policy if exists "Users can read own preferences" on public.user_preferences;
drop policy if exists "Users can insert own preferences" on public.user_preferences;
drop policy if exists "Users can update own preferences" on public.user_preferences;
drop policy if exists "Users can delete own preferences" on public.user_preferences;
drop policy if exists "Users can read own daily usage" on public.daily_usage;
drop policy if exists "Users can insert own daily usage" on public.daily_usage;
drop policy if exists "Users can update own daily usage" on public.daily_usage;
drop policy if exists "Users can read own life mode sessions" on public.life_mode_sessions;
drop policy if exists "Users can insert own life mode sessions" on public.life_mode_sessions;
drop policy if exists "Users can update own life mode sessions" on public.life_mode_sessions;
drop policy if exists "Users can read own life mode decisions" on public.life_mode_decisions;
drop policy if exists "Users can insert own life mode decisions" on public.life_mode_decisions;

create policy "Users can read their own decision history"
on public.decision_history for select
using (auth.uid() = user_id);

create policy "Users can insert their own decision history"
on public.decision_history for insert
with check (auth.uid() = user_id);

create policy "Users can update own history"
on public.decision_history for update
using (auth.uid() = user_id);

create policy "Profiles are readable by everyone"
on public.profiles for select
using (true);

create policy "Users can insert own profile"
on public.profiles for insert
with check (auth.uid() = id);

create policy "Users can update own profile"
on public.profiles for update
using (auth.uid() = id);

create policy "Group decisions are readable by everyone"
on public.group_decisions for select
using (true);

create policy "Authenticated users can create group decisions"
on public.group_decisions for insert
with check (auth.uid() = owner_id or owner_id is null);

create policy "Owners can update group decisions"
on public.group_decisions for update
using (auth.uid() = owner_id or owner_id is null);

create policy "Group preferences are readable by everyone"
on public.group_preferences for select
using (true);

create policy "Anyone can insert group preferences"
on public.group_preferences for insert
with check (true);

create policy "Referrals visible to involved users"
on public.referrals for select
using (auth.uid() = referrer_id or auth.uid() = referred_id);

create policy "Users can insert referral they are part of"
on public.referrals for insert
with check (auth.uid() = referrer_id or auth.uid() = referred_id);

create policy "Daily dilemmas readable by everyone"
on public.daily_dilemmas for select
using (true);

create policy "Authenticated users can create daily dilemmas"
on public.daily_dilemmas for insert
with check (auth.uid() is not null);

create policy "Authenticated users can update daily dilemmas"
on public.daily_dilemmas for update
using (auth.uid() is not null);

create policy "Daily votes readable by everyone"
on public.daily_dilemma_votes for select
using (true);

create policy "Users can cast own daily vote"
on public.daily_dilemma_votes for insert
with check (auth.uid() = user_id);

create policy "Users can update own daily vote"
on public.daily_dilemma_votes for update
using (auth.uid() = user_id);

create policy "Users can read own preferences"
on public.user_preferences for select
using (auth.uid() = user_id);

create policy "Users can insert own preferences"
on public.user_preferences for insert
with check (auth.uid() = user_id);

create policy "Users can update own preferences"
on public.user_preferences for update
using (auth.uid() = user_id);

create policy "Users can delete own preferences"
on public.user_preferences for delete
using (auth.uid() = user_id);

create policy "Users can read own daily usage"
on public.daily_usage for select
using (auth.uid() = user_id);

create policy "Users can insert own daily usage"
on public.daily_usage for insert
with check (auth.uid() = user_id);

create policy "Users can update own daily usage"
on public.daily_usage for update
using (auth.uid() = user_id);

create policy "Users can read own life mode sessions"
on public.life_mode_sessions for select
using (auth.uid() = user_id);

create policy "Users can insert own life mode sessions"
on public.life_mode_sessions for insert
with check (auth.uid() = user_id);

create policy "Users can update own life mode sessions"
on public.life_mode_sessions for update
using (auth.uid() = user_id);

create policy "Users can read own life mode decisions"
on public.life_mode_decisions for select
using (auth.uid() = user_id);

create policy "Users can insert own life mode decisions"
on public.life_mode_decisions for insert
with check (auth.uid() = user_id);
