import { useEffect } from "react";
import { Link, useLocation } from "react-router-dom";
import { applyPageMeta } from "./seoMeta.jsx";

function LegalDocShell({ title, description, path, children }) {
  const { pathname } = useLocation();
  useEffect(() => {
    applyPageMeta({ title, description, path: path || pathname });
  }, [title, description, path, pathname]);

  return (
    <article className="legal-doc card premium">
      <header className="legal-doc-header">
        <p className="hero-kicker">Legal</p>
        <h1 className="legal-doc-title">{title}</h1>
        <p className="meta legal-doc-updated">Last updated: 9 May 2026 · Decide For Me (“we”, “us”) operates decideforme.org</p>
      </header>
      <div className="legal-doc-body">{children}</div>
      <footer className="legal-doc-footer">
        <p className="meta">
          Questions?{" "}
          <a href="mailto:support@decideforme.org" className="legal-doc-link">
            support@decideforme.org
          </a>
        </p>
        <nav className="legal-doc-crossnav" aria-label="Other legal pages">
          <Link to="/terms">Terms</Link>
          <Link to="/privacy">Privacy</Link>
          <Link to="/cookies">Cookies</Link>
          <Link to="/">Home</Link>
        </nav>
      </footer>
    </article>
  );
}

export function TermsOfServicePage() {
  return (
    <LegalDocShell
      title="Terms of Service"
      description="Terms of Service for Decide For Me (decideforme.org) — subscriptions, AI disclaimer, referrals, and liability."
      path="/terms"
    >
      <section className="legal-section">
        <h2>1. Agreement</h2>
        <p>
          By accessing or using Decide For Me (“the Service”), you agree to these Terms. If you do not agree, do not use the Service. We may
          update these Terms; continued use after changes constitutes acceptance. Material changes will be indicated by updating the “Last
          updated” date above.
        </p>
      </section>
      <section className="legal-section">
        <h2>2. The Service</h2>
        <p>
          Decide For Me provides AI-assisted decision-making features, including chat-based recommendations, Life Mode, group tools, daily
          dilemmas, and related functionality. The Service is offered for personal, non-commercial use unless we agree otherwise in writing.
        </p>
      </section>
      <section className="legal-section">
        <h2>3. Accounts & eligibility</h2>
        <p>You must provide accurate registration information and keep your credentials secure. You are responsible for activity under your account.</p>
      </section>
      <section className="legal-section">
        <h2>4. Subscriptions, trials & billing</h2>
        <ul>
          <li>
            <strong>Pro subscriptions</strong> are billed via Stripe in the currency shown at checkout. Fees are charged according to the plan you select (e.g. monthly or yearly).
          </li>
          <li>
            <strong>Free trial</strong> — where offered, the trial length is displayed at checkout and on our pricing information before you subscribe. After the trial, your paid subscription begins unless you cancel in accordance with Stripe and these Terms.
          </li>
          <li>
            <strong>Taxes</strong> — prices may exclude applicable taxes, which may be added where required.
          </li>
        </ul>
      </section>
      <section className="legal-section">
        <h2>5. Cancellation</h2>
        <p>
          You may cancel your subscription through the billing workflow provided by Stripe (customer portal or as linked from your account where
          available). Cancellation stops future renewals; it does not necessarily refund past charges unless required by law or our refund policy
          below.
        </p>
      </section>
      <section className="legal-section">
        <h2>6. Refunds</h2>
        <p>
          Unless mandatory consumer rights apply in your jurisdiction, payments are generally <strong>non-refundable</strong>. If you believe a charge is in
          error or you have a statutory cooling-off right, contact{" "}
          <a href="mailto:support@decideforme.org">support@decideforme.org</a> within 14 days of purchase with your account email and transaction
          details. We will assess refund requests in line with applicable law and fairness; approval is not guaranteed except where the law requires.
        </p>
      </section>
      <section className="legal-section">
        <h2>7. AI-generated content disclaimer</h2>
        <p>
          Outputs are generated by artificial intelligence and are <strong>not professional, legal, medical, financial, or therapeutic advice</strong>.
          They may be inaccurate, incomplete, or inappropriate for your situation. You are solely responsible for decisions you make and actions you
          take. Do not rely on the Service for emergencies — contact emergency services or qualified professionals where appropriate.
        </p>
      </section>
      <section className="legal-section">
        <h2>8. Referral & affiliate programme</h2>
        <p>
          Where we operate referral or affiliate features (including commissions on qualifying subscriptions), participation is subject to programme
          rules shown in the app, eligibility requirements (including payout thresholds and Stripe Connect onboarding where applicable), fraud
          prevention, and our right to withhold or reverse commissions in case of abuse, chargebacks, or breach of these Terms. Commission rates and
          mechanics may change with reasonable notice via the Service.
        </p>
      </section>
      <section className="legal-section">
        <h2>9. Acceptable use</h2>
        <p>You must not misuse the Service, attempt to bypass limits or security, scrape or overload infrastructure, harass others, or break the law.</p>
      </section>
      <section className="legal-section">
        <h2>10. Intellectual property</h2>
        <p>
          We retain rights in the Service, branding, and software. You receive a limited, revocable licence to use the Service for its intended
          purpose. User content you submit remains yours; you grant us a licence to process it to operate and improve the Service.
        </p>
      </section>
      <section className="legal-section">
        <h2>11. Provided “as is”</h2>
        <p>
          The Service is provided <strong>“as is” and “as available”</strong> without warranties of any kind, express or implied, including merchantability,
          fitness for a particular purpose, or non-infringement, to the fullest extent permitted by law.
        </p>
      </section>
      <section className="legal-section">
        <h2>12. Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, we are not liable for indirect, incidental, special, consequential, or punitive damages, or loss
          of profits, data, or goodwill. Our aggregate liability arising out of these Terms or the Service is limited to the greater of (a) amounts
          you paid us in the twelve months before the claim or (b) £50, except where liability cannot be excluded by law.
        </p>
      </section>
      <section className="legal-section">
        <h2>13. Termination</h2>
        <p>We may suspend or terminate access for breach of these Terms or operational reasons, subject to applicable law.</p>
      </section>
      <section className="legal-section">
        <h2>14. Governing law</h2>
        <p>
          These Terms are governed by the laws of England and Wales. Courts of England and Wales have exclusive jurisdiction, subject to mandatory
          consumer protections where you reside.
        </p>
      </section>
    </LegalDocShell>
  );
}

export function PrivacyPolicyPage() {
  return (
    <LegalDocShell
      title="Privacy Policy"
      description="How Decide For Me collects, uses, and protects personal data (UK GDPR aligned)."
      path="/privacy"
    >
      <section className="legal-section">
        <h2>1. Who we are</h2>
        <p>
          The operator of Decide For Me (“we”) processes personal data in connection with decideforme.org and related apps. For data protection
          enquiries: <a href="mailto:support@decideforme.org">support@decideforme.org</a>.
        </p>
      </section>
      <section className="legal-section">
        <h2>2. Data we collect</h2>
        <ul>
          <li>
            <strong>Account data</strong> — email, authentication identifiers, profile fields you provide (e.g. username), referral codes, subscription and
            billing-related identifiers we receive from Stripe.
          </li>
          <li>
            <strong>Usage & content</strong> — prompts, decisions, chat messages, Life Mode activity, votes, preferences extracted or stored to personalise
            the Service.
          </li>
          <li>
            <strong>Technical data</strong> — IP address, device/browser type, approximate location if you enable location features, cookies and similar
            technologies as described in our <Link to="/cookies">Cookie Policy</Link>.
          </li>
          <li>
            <strong>Communications</strong> — messages you send to support.
          </li>
        </ul>
      </section>
      <section className="legal-section">
        <h2>3. Purposes & legal bases (UK GDPR)</h2>
        <ul>
          <li>
            <strong>Performance of contract</strong> — providing accounts, AI features, subscriptions, referrals, and customer support.
          </li>
          <li>
            <strong>Legitimate interests</strong> — securing the Service, analytics, product improvement, fraud prevention, and communicating service updates
            (balanced against your rights).
          </li>
          <li>
            <strong>Consent</strong> — where required for optional cookies or marketing communications (you may withdraw consent).
          </li>
          <li>
            <strong>Legal obligation</strong> — compliance with applicable law.
          </li>
        </ul>
      </section>
      <section className="legal-section">
        <h2>4. Subscriptions & payments</h2>
        <p>
          Payment processing is handled by Stripe. We receive limited billing metadata (e.g. customer and subscription identifiers, payment status) — not
          your full card number. Stripe’s privacy notice applies to payment data they process.
        </p>
      </section>
      <section className="legal-section">
        <h2>5. Referrals & commissions</h2>
        <p>
          If you participate in referrals or affiliate payouts, we process identifiers and earnings data necessary to attribute sign-ups, calculate
          commissions, and facilitate payouts (including Stripe Connect account identifiers where used).
        </p>
      </section>
      <section className="legal-section">
        <h2>6. AI processing</h2>
        <p>
          Content you submit may be processed by AI models via our infrastructure or subprocessors to generate responses. Do not submit special
          category data unless strictly necessary; we do not intend to process health data as part of the core Service.
        </p>
      </section>
      <section className="legal-section">
        <h2>7. Retention</h2>
        <p>
          We retain data only as long as needed for the purposes above, legal obligations, or dispute resolution. Account data may be deleted or
          anonymised when no longer required; some records may be retained longer where law requires (e.g. tax/finance).
        </p>
      </section>
      <section className="legal-section">
        <h2>8. Sharing & transfers</h2>
        <p>
          We may share data with hosting providers, AI inference providers, email delivery (if used), analytics (where permitted), and Stripe. Some
          subprocessors may be outside the UK — we use appropriate safeguards (e.g. UK-approved mechanisms) where required.
        </p>
      </section>
      <section className="legal-section">
        <h2>9. Security</h2>
        <p>
          We implement technical and organisational measures appropriate to the risk; no online service is completely secure. Notify us promptly if
          you suspect unauthorised account access.
        </p>
      </section>
      <section className="legal-section">
        <h2>10. Your rights</h2>
        <p>
          Subject to UK GDPR / Data Protection Act 2018, you may have rights to access, rectify, erase, restrict or object to processing, data
          portability, and to lodge a complaint with the ICO (
          <a href="https://ico.org.uk" target="_blank" rel="noreferrer">
            ico.org.uk
          </a>
          ). Contact us to exercise rights.
        </p>
      </section>
      <section className="legal-section">
        <h2>11. Children</h2>
        <p>The Service is not directed at children under 13 (or the minimum age in your jurisdiction). Do not register if you are underage.</p>
      </section>
      <section className="legal-section">
        <h2>12. Changes</h2>
        <p>We may update this Policy; the date at the top will change. Continued use after updates constitutes notice where permitted by law.</p>
      </section>
    </LegalDocShell>
  );
}

export function CookiePolicyPage() {
  return (
    <LegalDocShell
      title="Cookie Policy"
      description="How Decide For Me uses cookies and similar technologies."
      path="/cookies"
    >
      <section className="legal-section">
        <h2>1. What are cookies?</h2>
        <p>
          Cookies are small text files stored on your device. Similar technologies include local storage and session storage. They help the Service
          function, remember preferences, and understand usage.
        </p>
      </section>
      <section className="legal-section">
        <h2>2. How we use them</h2>
        <ul>
          <li>
            <strong>Essential</strong> — session/authentication tokens (e.g. Supabase session), security, load balancing, remembering onboarding or UI choices
            necessary for operation.
          </li>
          <li>
            <strong>Functional</strong> — storing preferences such as currency or feature flags where applicable.
          </li>
          <li>
            <strong>Analytics</strong> — where enabled, aggregated usage to improve the product (we minimise personal data in analytics).
          </li>
        </ul>
      </section>
      <section className="legal-section">
        <h2>3. Third parties</h2>
        <p>
          Payment pages may set cookies controlled by Stripe. Embedded content or maps (if any) may set their own cookies subject to their policies.
        </p>
      </section>
      <section className="legal-section">
        <h2>4. Managing cookies</h2>
        <p>
          You can block or delete cookies via browser settings; disabling essential cookies may break login or core features. For analytics opt-outs,
          use browser controls or contact us if we offer a preference centre.
        </p>
      </section>
      <section className="legal-section">
        <h2>5. Contact</h2>
        <p>
          Questions about cookies or this policy:{" "}
          <a href="mailto:support@decideforme.org">support@decideforme.org</a>. See also our{" "}
          <Link to="/privacy">Privacy Policy</Link>.
        </p>
      </section>
    </LegalDocShell>
  );
}
